server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chow100/springcloud-config.git  #填写你自己的github路径
          #uri: git@github.com:chow100/cloud2020.git  #不能用ssh地址，启动报错
          search-paths:
            - springcloud-config
      label: master  #读取分支
  rabbitmq:
    host: localhost
    port: 5672  #默认端口号不是15672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka  #注册进eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'